/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Button: typeof import('antd')['Button']
  const Input: typeof import('antd')['Input']
  const Typography: typeof import('antd')['Typography']
}
